### ISSUE TITLE
log file does not include new lines and only updates on every flush instead of every line

### ISSUE THREAD

**Issue by WebFreak001** [Extrawurst/forever-d#7]
It won't update the log file until it has written like 4096 bytes, even though in the console it works just fine. Used vibe.d `logInfo` to do this

**Comment by Extrawurst** [comment]
i guess we need to manually flush the outStreams. can you provide the full vibe.d program to reproduce the problem ?

**Comment by WebFreak001** [comment]
It isn't only a problem with vibe.d, it also occurs with std.stdio:
```d
import core.thread;
import std.stdio : writeln;

void main()
{
        while(true) {
                for(int i = 0; i < 10; i++)
                        writeln("Hello World");
                Thread.sleep(300.msecs);
        }
}
```

```
dmd test.d
forever-d -l test.txt ./test &
cat test.txt
cat test.txt
cat test.txt
...
```
Here you will see that it will take at least a minute or so until it says anything in the file. And then also the new lines are missing

**Comment by Extrawurst** [comment]
@WebFreak001 so this issue boiled down mainly to how the child process buffers it's output. by disabling  buffering in the reproduction case:
`std.stdio.stdout.setvbuf(null,_IONBF);`

although I heavily refactored the whole program that it may also be fixed by that, I did not test the old forever-d yet with the non-buffering test app.
